TARGET = multithread_practice multithread_practice_solution

all: $(TARGET)

multithread_practice: multithread_practice.c
	gcc -o multithread_practice multithread_practice.c

multithread_practice_solution: multithread_practice_solution.c
	gcc -o multithread_practice_solution multithread_practice_solution.c -lpthread

clean:
	rm $(TARGET)
